version: "3.8"

services:
################################################################################

    php-fpm:
        image: symfo_php:8.2-fpm-alpine
        container_name: symfo_recipes
        # restart: always
        ports:
            - 8000:8000
        links:
            - mysql:mysql_host
        depends_on:
            - mysql
        volumes:
            - ./app:/var/www/html

################################################################################

    mysql:
        image: mysql:latest
        container_name: symfo_mysql2
        # restart: always
        ports:
            - '8002:3306'
        # command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: mysqlpw
            MYSQL_DATABASE: recipes_db
            MYSQL_USER: recipes_db
            MYSQL_PASSWORD: mysqlpw

################################################################################

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: symfo_phpmyadmin2
        # restart: always
        ports:
            - '8001:80'
        links:
            - mysql:mysql_host
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql_host
            PMA_PORT: 3306

################################################################################
